
#Seed function --is used to save the state of a random function, so that it can generate same random numbers on multiple executions of the code on the same machine or on different machines (for a specific seed value). The seed value is the previous value number generated by the generator.

import random  
for i in range(5):  
    # Any number can be used in place of '0'. 
    random.seed(0)  
    # Generated random number will be between 1 to 1000. 
    print(random.randint(1, 1000))  


#----------------------------

import random 
  
# print a random number between 1 and 1000. 
print(random.randint(1, 1000)) 
  
# if you want to get the same random number again then, 
random.seed(3)  
print(random.randint(1, 1000)) 
  
# If seed function is not used 
  
# Gives totally unpredictable responses. 
print(random.randint(1, 1000))  




